# Generated by Django 3.0.3 on 2020-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_parser_app', '0002_auto_20200617_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.TextField(default='₽', verbose_name='Валюта'),
        ),
    ]
