# Generated by Django 3.0.3 on 2020-06-17 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_parser_app', '0003_auto_20200617_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 0, 3, 34, 125293), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.TextField(blank=True, default='₽', null=True, verbose_name='Валюта'),
        ),
    ]
